name: flutter_music_player
description: Music Player App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  audioplayers: ^4.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
